<?php
 
// fichier de langues en français
 
 //generique
 
 define("_envoyer","Envoyer");
 
// Acceuil
define("_Accueil","Accueil");
define("_Services","Services");
define("_Qui_nous_sommes","Qui nous sommes ?");
define("_Contactez_nous","Contactez-nous");

//Presentation
define("_H_Presentation_1","plus besoin de prendre congé pour aller à vos services");
define("_H_Presentation_2","auto");
define("_H_Presentation_3","Nos prestataires déplacent vos véhicules");
 define("_H_Presentation_4","Nous effectuons tous les déplacements automobile pour vous dans les meilleurs délais.");
define("_H_Presentation_5","Ces déplacements automobile sont assurés en partenariat avec ");
define("_H_Presentation_6"," et ");

//Offre particulier
define("_H_Presentation_7","Nos prestataires sont sélectionnés et évalués sur un ensemble de critères qualités.");
define("_Offre_Particulier_1","Particuliers");
define("_Offre_Particulier_2","35€/par heure");
define("_Offre_Particulier_3","Assurance OMINIUM");
define("_Offre_Particulier_4","Prestataires de qualité****");
define("_Offre_Particulier_5","Possibilité d'annulation jusqu'à 8h avant");
define("_Offre_Particulier_6","Profiter des avantages et cumuler des heures");
define("_Offre_Particulier_7","Prendre un rendez-vous");

//offre entreprise
define("_Offre_Entreprise_1","Entreprises");
define("_Offre_Entreprise_2","Par devis");
define("_Offre_Entreprise_3","Assurance OMINIUM");
define("_Offre_Entreprise_4","Prestataires de qualité****");
define("_Offre_Entreprise_5","Suivi et localisation de vos véhicules");
define("_Offre_Entreprise_6","Possibilité d'annulation jusqu'à 2h avant");
define("_Offre_Entreprise_7","Profiter des avantages et cumuler des heures");
define("_Offre_Entreprise_8","Demander un devis");

//Portfolio 


define("_Portfolio_1","Les déplacements vers vos services");
define("_Portfolio_2","auto");
define("_Portfolio_3","Passage au contrôle technique");
define("_Portfolio_4","Entretien & réparation mécanique");
define("_Portfolio_5","Montage & changement pneumatique");
define("_Portfolio_6","Réparation carrosserie");
define("_Portfolio_7","Réparation vitrage");
define("_Portfolio_8","Lavage & nettoyage");

//about


define("_about_1","Qui nous sommes ?");
define("_about_2","Services");
define("_about_3","Auto");
define("_about_4"," est une plateforme collaborative agrée en Belgique et axée sur les déplacements de vos véhicules. Vous avez besoin de faire passer votre véhicule au contrôle technique ou un entretien chez votre mécanicien ou une réparation chez votre carrossier ou encore pour un lavage ou des changements de pneux. L'un de nos prestataires s'occupera de déplacer vos véhicules vers vos services automobiles. Tous les prestataires sont sélectionnés et évalués sur un ensemble de critères qualités ainsi que par nos clients afin de vous garantir le meilleur service.");
define("_about_5","Les prestataires s'occupent de récupèrer votre véhicule à votre domicile ou sur votre lieu de travail et se chargent de le déplacer vers l'un des services automobiles que vous souhaitez effectuer. Ensuite, ils vous livrent votre véhicule à votre domicile ou sur votre lieu de travail. Les propriétaires des véhicules bénéficient une couverture d'assurance OMNIUM en partenariat avec ETHIAS et TOURING lors des déplacements. ");

//contact
define("_contact_1","Contactez-nous");
define("_contact_2","Name");
define("_contact_3","Veuillez entrer votre nom et prénom.");
define("_contact_4","Email Address");
define("_contact_5","Veuillez entrer votre Email.");
define("_contact_6","Phone Number");
define("_contact_7","Message");
define("_contact_8","Veuillez entrer votre message.");
define("_contact_9","Envoyer");
define("_contact_10","Ces champs sont obligatoires.");


//footer social media
define("_social_media_1","Email & social media");
define("_social_media_2","Inscrivez-vous à notre Newsletter");
define("_social_media_3","Recevez 15% de réduction sur votre prochain service auto.");
define("_social_media_4","Entrez votre email");
define("_social_media_5","s'inscrire");

//formulaire precommande

define("_precommande_services_souhaitez","Sélectionnez le service que vous souhaitez effectuer");
define("_precommande_selection_service","Veuillez sélectionner le service que vous souhaitez effectuer.");
define("_precommande_choisir","Choisir...");
define("_precommande_CT","Contrôle technique");
define("_precommande_entretien_reparation","Entretien & réparation automobile");
define("_precommande_pneu_auto","Pneus automobile");
define("_precommande_reparation_carroserie","Réparation de carrosserie automobile");
define("_precommande_reparation_vitrage","Réparation de vitrage automobile");
define("_precommande_lavage","Lavage automobile");
define("_precommande_deplacement","Déplacement automobile");
define("_precommande_date_service","Date d'exécution du service choisi");
define("_precommande_adresse_vehicule","L'adresse de localisation de votre véhicule");
define("_precommande_cp","Code postal");
define("_precommande_label_ville","Ville");
define("_precommande_ville","Bruxelles");
define("_precommande_label_adresse_service","L'adresse de localisation du service choisi ");
define("_precommande_adresse_service","Rue Neuve 30");
define("_precommande_label_nom_prenom","Votre nom & prénom");
define("_precommande_nom_prenom","Veuillez entrer votre nom & prénom.");
define("_precommande_email","Votre Email");
define("_precommande_label_telephone","Votre n° téléphone");
define("_precommande_telephone","Veuillez entrer votre n° de téléphone.");
define("_precommande_label_votre_message","Votre message");
define("_precommande_votre_message","Bonjour, je souhaite effectuer le passage au contrôle technique. Pourriez-vous ...");


//precommande ct

define("_precommande_ct_text1","Le trajet aller + le passage au contrôle technique + le trajet retour = +- 2h15 en moyenne à Bruxelles.");
define("_precommande_ct_text2","Vous devez passer votre véhicule au contrôle technique, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail et ils se chargent effectuer le passage au contrôle technique. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

//precommande entretien reparation
define("_precommande_entretien_reparation_text_1","Le trajet aller + le trajet retour vers l'un des garages de votre choix = +- 1h en moyenne à Bruxelles.");
define("_precommande_entretien_reparation_text_2","Vous devez effectuer un entretien ou une réparation chez votre garagiste, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail. Ensuite, ils se chargent de déplacer votre véhicule chez votre garagiste. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

//precommande pneu auto
define("_precommande_pneu_auto_text_1","Le trajet aller + le trajet retour vers l'un des garages de votre choix = +- 1h en moyenne à Bruxelles.");
define("_precommande_pneu_auto_text_2","Vous devez effectuer un changement de pneus chez votre garagiste, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail. Ensuite, ils se chargent de déplacer votre véhicule chez votre garagiste. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

// precommande reparation carroserie
define("_precommande_reparation_carroserie_text_1","Le trajet aller + le trajet retour vers l'un des garages de votre choix = +- 1h en moyenne à Bruxelles.");
define("_precommande_reparation_carroserie_text_2","Vous devez effectuer une réparation chez votre carrossier, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail. Ensuite, ils se chargent de déplacer votre véhicule chez votre carrossier. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

//precommande reparation vitrage

define("_precommande_reparation_vitrage_text_1","Le trajet aller + le trajet retour vers l'un des garages de votre choix = +- 1h en moyenne à Bruxelles.");
define("_precommande_reparation_vitrage_text_2","Vous devez effectuer une réparation de vitrage chez votre garagiste, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail. Ensuite, ils se chargent de déplacer votre véhicule chez votre garagiste. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

//precommande lavage

define("_precommande_lavage_text_1","Le trajet aller + le passage au carwash + le trajet retour vers l'un des carwashs de votre choix = +- 1h45 en moyenne à Bruxelles.");
define("_precommande_lavage_text_2","Vous devez effectuer un lavage chez votre carwash, nos prestataires s'occupent de récupérer votre véhicule à votre domicile ou sur votre lieu de travail. Ensuite, ils se chargent de déplacer votre véhicule chez votre carwash. Lorsque le service est effectué, ils peuvent également se charger de vous livrer votre véhicule.");

// etc ...
 
?>