<?php
define("_envoyer","Versturen");
define("_Accueil","Huis");
define("_Services","Diensten");
define("_Qui_nous_sommes","Wie we zijn ?");
define("_Contactez_nous","Neem contact met ons op");
define("_H_Presentation_1","geen behoefte om afscheid te nemen om voor je te zorgen");
define("_H_Presentation_2","auto");
define("_H_Presentation_3","Onze parkeergarage verplaatst uw auto waar u maar wilt");
define("_H_Presentation_4","Wij maken alle verplaatsing van uw auto zo snel mogelijk voor u.");
define("_H_Presentation_5","Verplaatsing van auto's is gedekt door een verzekering");
define("_H_Presentation_6","en");
define("_H_Presentation_7","Onze dienstverleners worden geselecteerd en beoordeeld op basis van een reeks kwaliteitscriteria.");
define("_Offre_Particulier_1","individuen");
define("_Offre_Particulier_2","35 € / per uur");
define("_Offre_Particulier_3","Verzekering");
define("_Offre_Particulier_4","Kwaliteitsaanbieders ****");
define("_Offre_Particulier_5","Mogelijkheid tot annulering tot 8 uur eerder");
define("_Offre_Particulier_6","Geniet van de voordelen en verzamel uren");
define("_Offre_Particulier_7","Maak een afspraak");
define("_Offre_Entreprise_1","bedrijven");
define("_Offre_Entreprise_2","Door citaat");
define("_Offre_Entreprise_3","Verzekering");
define("_Offre_Entreprise_4","Kwaliteitsaanbieders ****");
define("_Offre_Entreprise_5","Voertuigen opsporen en lokaliseren");
define("_Offre_Entreprise_6","Mogelijkheid tot annulering tot 2 uur eerder");
define("_Offre_Entreprise_7","Geniet van de voordelen en verzamel uren");
define("_Offre_Entreprise_8","Vraag een offerte aan");
define("_Portfolio_1","Soorten verplaatsingen");
define("_Portfolio_2","auto");
define("_Portfolio_3","Technische inspectie doorgeven");
define("_Portfolio_4","Mechanisch onderhoud & reparatie");
define("_Portfolio_5","Montage & pneumatische verandering");
define("_Portfolio_6","Lichaamsherstel");
define("_Portfolio_7","Beglazing reparaties");
define("_Portfolio_8","Wassen en schoonmaken");
define("_about_1","Wie we zijn ?");
define("_about_2","Diensten");
define("_about_3","Auto");
define("_about_4","is gericht op autoritreizen. U moet uw voertuig laten nakijken door uw monteur of repareren in uw carrosseriebedrijf of om een wasbeurt of bandenwissel. Een van onze valet zorgt voor het verplaatsen van uw voertuig. Alle serviceproviders worden geselecteerd en beoordeeld op basis van een reeks kwaliteitscriteria en ook door onze klanten om u de beste service te garanderen.");
define("_about_5","Onze valets zorgen ervoor dat u uw voertuig bij u thuis of op de werkplek ophaalt en deze naar een van de autodiensten verplaatst die u wilt doen. ze kunnen dan, als u dat wenst, uw voertuig terugbrengen zodra de tussenkomst van uw automonteur is beëindigd. Voertuigeigenaren zijn verzekerd tijdens de verplaatsing.");
define("_contact_1","Neem contact met ons op");
define("_contact_2","Naam");
define("_contact_3","Voer uw voor- en achternaam in.");
define("_contact_4","E-mailadres");
define("_contact_5","Vul alstublieft uw e-mailadres in.");
define("_contact_6","Telefoonnummer");
define("_contact_7","Bericht");
define("_contact_8","Vul alstublieft uw bericht in");
define("_contact_9","Versturen");
define("_contact_10","Deze velden zijn verplicht.");
define("_social_media_1","E-mail en sociale media");
define("_social_media_2","Abonneer u op onze nieuwsbrief");
define("_social_media_3","Ontvang 15% korting op uw volgende autoservice.");
define("_social_media_4","Voer uw e-mailadres in");
define("_social_media_5","Selecteer de service die u wilt uitvoeren");
define("_precommande_selection_service","Selecteer de service die u wilt uitvoeren.");
define("_precommande_choisir","Kiezen...");
define("_precommande_CT","Technische controle");
define("_precommande_entretien_reparation","Auto onderhoud en reparatie");
define("_precommande_pneu_auto","Autobanden");
define("_precommande_reparation_carroserie","Auto carrosserieherstel");
define("_precommande_reparation_vitrage","Auto Glass Repair");
define("_precommande_lavage","Carwash");
define("_precommande_deplacement","auto verplaatsing");
define("_precommande_date_service","Uitvoeringsdatum van de gekozen service");
define("_precommande_adresse_vehicule","Het locatieadres van uw voertuig");
define("_precommande_cp","Postcode");
define("_precommande_label_ville","stad");
define("_precommande_ville","Brussel");
define("_precommande_label_adresse_service","Het locatie-adres van de gekozen service");
define("_precommande_adresse_service","Rue Neuve 30");
define("_precommande_label_nom_prenom","Uw naam en voornaam");
define("_precommande_nom_prenom","Voer uw naam en voornaam in.");
define("_precommande_email","Jouw email");
define("_precommande_label_telephone","Jouw telefoon nummer");
define("_precommande_telephone","Voer uw telefoonnummer in.");
define("_precommande_label_votre_message","Uw bericht");
define("_precommande_votre_message","Hallo, ik wens de technische inspectie te maken. Kunt u ...");
define("_precommande_ct_text1","De verplaatsing in één richting + de overgang naar technische inspectie + verplaatsing van de terugkeer = + - 2u15 gemiddeld in Brussel.");
define("_precommande_ct_text2","U moet uw voertuig doorgeven aan de technische inspectie die door onze parkeerservice wordt uitgevoerd om uw voertuig op te pikken in uw woonplaats of op uw werkplek en zij zorgen voor de overgang naar de technische controle. Als de service klaar is, kunnen ze ook regelen dat u uw auto terugbrengt als u dat wilt.");
define("_precommande_entretien_reparation_text_1","De eenrichtingsverplaatsing + de retourverplaatsing naar een van de garages van uw keuze = + - gemiddeld 1 uur in Brussel.");
define("_precommande_entretien_reparation_text_2","U moet onderhoud of reparaties uitvoeren in uw garage, onze parkeers zorgen voor het oppakken van uw voertuig bij u thuis of op uw werkplek. Dan zorgen ze ervoor dat uw voertuig naar uw garage wordt verplaatst. Als de service klaar is, kunnen ze ook regelen dat u uw auto terugbrengt als u dat wilt.");
define("_precommande_pneu_auto_text_1","De eenrichtingsverplaatsing + de retourverplaatsing naar een van de garages van uw keuze = + - gemiddeld 1 uur in Brussel.");
define("_precommande_pneu_auto_text_2","U moet een bandenwissel in uw garage maken, onze parkeerservice zorgt voor uw voertuig bij u thuis of op uw werkplek. Dan zorgen ze ervoor dat uw voertuig naar uw garage wordt verplaatst. Als de service klaar is, kunnen ze ook regelen dat u uw auto terugbrengt als u dat wilt.");
define("_precommande_reparation_carroserie_text_1","De enkele reis + de terugreis naar een van de garages van uw keuze = + - gemiddeld 1 uur in Brussel.");
define("_precommande_reparation_carroserie_text_2","De eenrichtingsverplaatsing + de retourverplaatsing naar een van de garages van uw keuze = + - gemiddeld 1 uur in Brussel.");
define("_precommande_reparation_vitrage_text_2","De eenrichtingsverplaatsing + de doorgang naar de carwash + de retourverplaatsing naar een van de carwash naar keuze = + - 1u45 gemiddeld in Brussel.");
define("_precommande_lavage_text_2","U moet uw wasstraat wassen, onze bediende zorgt ervoor dat u uw voertuig ophaalt in uw woonplaats of op uw werkplek. Daarna zullen ze uw voertuig naar uw carwash verplaatsen. Als de service klaar is, kunnen ze ook regelen dat u uw auto terugbrengt als u dat wilt.");

?>